-- Round 2 — ALL database changes in one file (generated by concatenating the three files below, in this order).
--   1) 2026-10-04-profile-question-language.sql
--   2) 2026-10-04-questions-authoring.sql
--   3) 2026-10-04-password-resets.sql
-- Safe to run more than once (idempotent). Run it in Supabase -> SQL Editor BEFORE deploying the Round 2 API.
-- Verified on a throwaway Postgres 16: applied on top of the pre-Round-2 schema, run twice with no errors,
-- and the result matched core/src/db/schema.ts exactly (all tables, columns and nullability).

-- ===== profile-question-language =====
-- Round 2 (profile): student's preferred question language. Idempotent.
-- Not applied automatically; the owner runs this in the Supabase SQL editor.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS question_language text NOT NULL DEFAULT 'en';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'profiles_question_language_check'
  ) THEN
    ALTER TABLE public.profiles
      ADD CONSTRAINT profiles_question_language_check
      CHECK (question_language IN ('en', 'kn', 'both'));
  END IF;
END $$;

-- ===== questions-authoring =====
-- Round 2: question authoring (draft/published, edit tracking, revisions).
-- Idempotent. Apply manually in the Supabase SQL editor; not applied by any script.

ALTER TABLE questions
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'published',
  ADD COLUMN IF NOT EXISTS edited_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS updated_by uuid NULL REFERENCES profiles(id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'questions_status_check'
  ) THEN
    ALTER TABLE questions
      ADD CONSTRAINT questions_status_check CHECK (status IN ('draft', 'published'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS question_revisions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  question_id uuid NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  revision_no integer NOT NULL,
  snapshot jsonb NOT NULL,
  edited_by uuid NULL REFERENCES profiles(id),
  edited_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT question_revisions_question_no_unique UNIQUE (question_id, revision_no)
);

ALTER TABLE question_revisions ENABLE ROW LEVEL SECURITY;
-- No policies: only the API (service connection) reads/writes, like the other tables.

-- ===== password-resets =====
-- Audit table for teacher-set student password resets (Round 2, student-reset).
-- Idempotent. RLS on with no policies: only the API (service connection) touches it.
CREATE TABLE IF NOT EXISTS password_resets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid NOT NULL REFERENCES profiles(id),
  reset_by uuid NOT NULL REFERENCES profiles(id),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_password_resets_student ON password_resets (student_id);
ALTER TABLE password_resets ENABLE ROW LEVEL SECURITY;

-- ===== verification (run after the above; every row should say ok = true) =====
SELECT 'profiles.question_language' AS item,
       EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='question_language') AS ok
UNION ALL SELECT 'questions.status',
       EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='questions' AND column_name='status')
UNION ALL SELECT 'questions.edited_at',
       EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='questions' AND column_name='edited_at')
UNION ALL SELECT 'questions.updated_by',
       EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='questions' AND column_name='updated_by')
UNION ALL SELECT 'table question_revisions',
       EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='question_revisions')
UNION ALL SELECT 'table password_resets',
       EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='password_resets');
