import { newPage, login, BASE, closeBrowser, check, summary, dbq, mockPassword } from './lib.mjs';
const p = await newPage(); p.setDefaultTimeout(8000);
const step = (t) => console.log('\n## ' + t);
const vis = (loc) => loc.first().isVisible().catch(() => false);
const calls = (since) => p.reqs.slice(since);

step('Forgot password (teacher-first)');
await p.goto(BASE + '/login', { waitUntil: 'networkidle' });
await p.waitForTimeout(2500);
const link = p.getByRole('link', { name: /Forgot password/ });
check('login shows a "Forgot password?" link', await vis(link));
const deco = await link.first().evaluate((el) => getComputedStyle(el.querySelector('div,span') ?? el).textDecorationLine).catch(() => '');
check('link is underlined (looks like a link)', /underline/.test(deco), deco);
await link.first().click(); await p.waitForTimeout(1500);
check('opens /forgot-password', new URL(p.url()).pathname === '/forgot-password');
check('explains the teacher route', await vis(p.getByText('Your teacher gives you a temporary password.')));
check('no email form while email reset is off', !(await vis(p.getByText('Send reset link'))) && !(await vis(p.locator('input[placeholder="email"]:visible'))));
await p.getByRole('button', { name: /Back to sign in/ }).first().click(); await p.waitForTimeout(1200);
check('Back to sign in returns to login', new URL(p.url()).pathname === '/login');

step('Sign in as student s1 (Ananya), first-run tour');
await login(p, 's1@stemri.local');
check('feed loaded from API', p.reqs.some((r) => r.startsWith('GET /api/feed/today -> 200')));
check('first-run coach overlay shows', await vis(p.getByText('Swipe up for the next question')));
await p.getByRole('button', { name: /^Skip/ }).last().click().catch(() => {}); await p.waitForTimeout(800);
check('overlay can be skipped', !(await vis(p.getByText('Swipe up for the next question'))));

step('Answer lock and grading');
const q1 = await vis(p.getByText(/Question 1 of 15/));
check('shows Question 1 of 15', q1);
const listTop = () => p.evaluate(() => { const e = [...document.querySelectorAll('*')].find((x) => x.scrollHeight > x.clientHeight + 40 && x.clientHeight > 300); return e ? Math.round(e.scrollTop) : -1; });
await p.keyboard.press('ArrowDown'); await p.waitForTimeout(300);
check('"Answer first" hint appears when swiping an unanswered card', await vis(p.getByText(/Answer first/)));
await p.waitForTimeout(900);
check('ArrowDown blocked before answering (list did not move)', (await listTop()) === 0, String(await listTop()));
let n = p.reqs.length;
await p.getByText('Show Answer').first().click(); await p.waitForTimeout(1200);
const labels = await p.getByRole('button').evaluateAll((els) => els.map((e) => e.getAttribute('aria-label')).filter((l) => /^(Again|Average|Easy)$/.test(l || '')));
check('shows Again / Average / Easy', ['Again', 'Average', 'Easy'].every((l) => labels.includes(l)), JSON.stringify(labels));
await p.getByRole('button', { name: 'Average', exact: true }).first().click(); await p.waitForTimeout(2500);
check('answer submitted (200)', calls(n).some((r) => r.startsWith('POST /api/submissions -> 200')), calls(n).join(' | '));
await p.keyboard.press('ArrowDown'); await p.waitForTimeout(1500);
check('after answering, ArrowDown moves to the next card', (await listTop()) > 0, String(await listTop()));
check('submission row in DB', (await dbq("select count(*) from submissions where student_id='2881f8ca-3197-4a65-be6b-8bf1cdd953d0'")) === '1');

step('Profile');
await p.goto(BASE + '/profile', { waitUntil: 'networkidle' }); await p.waitForTimeout(3000);
check('shows name "Ananya"', await vis(p.getByText('Ananya', { exact: true })));
check('avatar initial is A', await vis(p.getByText('A', { exact: true })));
await p.getByRole('button', { name: /How it works/ }).first().click(); await p.waitForTimeout(1200);
check('How it works opens the tour inside Profile', await vis(p.getByText('Swipe up for the next question')));
await p.getByRole('button', { name: /^Next/ }).first().click(); await p.waitForTimeout(500);
check('tour step 2', await vis(p.getByText('Tap Show Answer, then rate yourself')));
await p.getByRole('button', { name: /^Next/ }).first().click(); await p.waitForTimeout(500);
check('tour step 3', await vis(p.getByText('Your streak and progress are up here')));
await p.getByRole('button', { name: /Got it|Done/ }).first().click(); await p.waitForTimeout(800);
check('tour closes', !(await vis(p.getByText('Your streak and progress are up here'))));

step('Edit name');
n = p.reqs.length;
await p.getByRole('button', { name: 'Edit name' }).first().click(); await p.waitForTimeout(600);
const nameInput = p.locator('input:visible').first();
await nameInput.fill('Ananya Rao');
await p.getByRole('button', { name: /^Save/ }).first().click(); await p.waitForTimeout(2000);
check('PATCH /api/me 200', calls(n).some((r) => r.startsWith('PATCH /api/me -> 200')), calls(n).join(' | '));
check('new name shown', await vis(p.getByText('Ananya Rao', { exact: true })));
check('name saved in DB', (await dbq("select full_name from profiles where id='2881f8ca-3197-4a65-be6b-8bf1cdd953d0'")) === 'Ananya Rao');

step('Question language');
n = p.reqs.length;
await p.getByRole('radio', { name: /ಕನ್ನಡ/ }).first().click(); await p.waitForTimeout(2000);
check('PATCH /api/me 200 for Kannada', calls(n).some((r) => r.startsWith('PATCH /api/me -> 200')), calls(n).join(' | '));
check('preference saved in DB = kn', (await dbq("select question_language from profiles where id='2881f8ca-3197-4a65-be6b-8bf1cdd953d0'")) === 'kn');
await p.goto(BASE + '/', { waitUntil: 'networkidle' }); await p.waitForTimeout(4000);
check('Kannada-only student sees no English questions', !(await vis(p.getByText(/Q\d+\/\d+/))));
await p.goto(BASE + '/profile', { waitUntil: 'networkidle' }); await p.waitForTimeout(2500);
await p.getByRole('radio', { name: /^English/ }).first().click(); await p.waitForTimeout(2000);
check('back to English in DB', (await dbq("select question_language from profiles where id='2881f8ca-3197-4a65-be6b-8bf1cdd953d0'")) === 'en');

step('Change password, then sign in with it');
await p.getByRole('button', { name: 'Change password' }).first().click(); await p.waitForTimeout(600);
const pwFields = p.locator('input[type=password]:visible');
check('two password fields appear', (await pwFields.count()) === 2);
await pwFields.nth(0).fill('short'); await pwFields.nth(1).fill('short');
await p.getByRole('button', { name: 'Update password' }).first().click(); await p.waitForTimeout(800);
check('short password rejected', await vis(p.getByText(/at least 8/)));
await pwFields.nth(0).fill('Brand#New2026'); await pwFields.nth(1).fill('Brand#New2026');
await p.getByRole('button', { name: 'Update password' }).first().click(); await p.waitForTimeout(2500);
check('password changed in auth store', (await mockPassword('s1@stemri.local')).password === 'Brand#New2026');

step('Per-account self-study decks');
await p.goto(BASE + '/(self-study)', { waitUntil: 'networkidle' }).catch(() => {}); await p.waitForTimeout(2500);
await p.getByText('New Deck').first().click(); await p.waitForTimeout(800);
await p.locator('input[placeholder="Deck title"]:visible').fill('Ananya private deck');
await p.getByText('Save', { exact: true }).first().click(); await p.waitForTimeout(2500);
check('deck created for s1', await vis(p.getByText('Ananya private deck')));
await p.goto(BASE + '/profile', { waitUntil: 'networkidle' }); await p.waitForTimeout(2000);
await p.getByRole('button', { name: 'Sign out' }).first().click(); await p.waitForTimeout(800);
await p.getByRole('button', { name: 'Sign out' }).last().click(); await p.waitForTimeout(3500);
check('signed out to login', new URL(p.url()).pathname === '/login');
await login(p, 's1@stemri.local', 'Stemri@2026');
check('old password no longer works', new URL(p.url()).pathname === '/login');
await login(p, 's2@stemri.local');
await p.goto(BASE + '/(self-study)', { waitUntil: 'networkidle' }).catch(() => {}); await p.waitForTimeout(2500);
check("s2 does not see s1's deck", !(await vis(p.getByText('Ananya private deck'))));

console.log('\nconsole/page errors:', p.logs.filter((l) => !/useNativeDriver|pointerEvents/.test(l)).slice(0, 6).join(' | ') || 'none');
const failed = summary();
await closeBrowser();
process.exit(failed ? 1 : 0);
