import { newPage, login, BASE, closeBrowser, check, summary, dbq, tokenFor, api, chip, openQuestions, pickTopic } from './lib.mjs';
const p = await newPage({ width: 420, height: 1200 }); p.setDefaultTimeout(9000);
const step = (t) => console.log('\n## ' + t);
const vis = (loc) => loc.first().isVisible().catch(() => false);
const since = (n) => p.reqs.slice(n);

step('Teacher shell');
await login(p, 'teacher@stemri.local');
const tabs = await p.getByRole('tab').allTextContents();
check('5 tabs: Today, Questions, Calendar, Reports, Profile', ['Today', 'Questions', 'Calendar', 'Performance', 'Profile'].every((t) => tabs.some((x) => x.includes(t))), JSON.stringify(tabs));

step('Create a DRAFT flashcard');
await openQuestions(p);
let n = p.reqs.length;
await p.getByText('New question').first().click(); await p.waitForTimeout(1500);
await pickTopic(p);
await chip(p, 'Flashcard').click(); await p.waitForTimeout(500);
await p.locator('textarea[placeholder="Type the question"]:visible').fill('DRAFT-Q: What is the SI unit of magnetic field?');
await p.locator('[placeholder="Type the answer"]:visible').fill('Tesla (T)');
await p.locator('[placeholder^="Why is this the answer"]:visible').fill('B is measured in tesla.');
await chip(p, 'Draft').click(); await p.waitForTimeout(300);
await p.getByRole('button', { name: 'Save', exact: true }).click(); await p.waitForTimeout(2500);
check('POST /api/questions 201', since(n).some((r) => r.startsWith('POST /api/questions -> 201')), since(n).join(' | '));
check('DB: draft, author recorded', (await dbq("select status||'|'||(created_by is not null) from questions where question_text like 'DRAFT-Q:%'")) === 'draft|true');
const s2 = await tokenFor('s2@stemri.local');
let feed = await api(s2, 'GET', '/api/feed/today');
check('draft is NOT in a student feed', feed.status === 200 && !JSON.stringify(feed.json).includes('DRAFT-Q'));
const draftId = await dbq("select id from questions where question_text like 'DRAFT-Q:%'");

step('Create a published KANNADA flashcard');
await p.getByText('New question').first().click(); await p.waitForTimeout(1500);
await pickTopic(p);
await chip(p, 'Flashcard').click(); await p.waitForTimeout(500);
await p.locator('textarea[placeholder="Type the question"]:visible').fill('ಕಾಂತೀಯ ಕ್ಷೇತ್ರ ಎಂದರೇನು?');
await p.locator('[placeholder="Type the answer"]:visible').fill('ಆಯಸ್ಕಾಂತದ ಸುತ್ತಲಿನ ಪ್ರದೇಶ.');
await p.locator('[placeholder^="Why is this the answer"]:visible').fill('ಕಾಂತೀಯ ಬಲ ಅನುಭವವಾಗುವ ಪ್ರದೇಶ.');
await chip(p, 'Kannada').click(); await p.waitForTimeout(300);
n = p.reqs.length;
await p.getByRole('button', { name: 'Save', exact: true }).click(); await p.waitForTimeout(2500);
check('Kannada question saved (201)', since(n).some((r) => r.startsWith('POST /api/questions -> 201')), since(n).join(' | '));
check('DB: language kn, published', (await dbq("select language||'|'||status from questions where question_text like 'ಕಾಂತೀಯ%'")) === 'kn|published');
feed = await api(s2, 'GET', '/api/feed/today');
check('English-pref student does NOT get the Kannada question', !JSON.stringify(feed.json).includes('ಕಾಂತೀಯ'));
await api(s2, 'PATCH', '/api/me', { question_language: 'both' });
feed = await api(s2, 'GET', '/api/feed/today');
check("'both'-pref student gets it", JSON.stringify(feed.json).includes('ಕಾಂತೀಯ'));
await api(s2, 'PATCH', '/api/me', { question_language: 'en' });

step('Edit, history, archive, restore, delete');
await openQuestions(p);
await p.getByPlaceholder('Search question text').fill('DRAFT-Q'); await p.waitForTimeout(1800);
check('search finds the draft', await vis(p.getByText(/DRAFT-Q: What is the SI unit/)));
check('draft badge shown', await vis(p.locator('text=Draft >> visible=true')));
await p.getByText(/DRAFT-Q: What is the SI unit/).first().click(); await p.waitForTimeout(2000);
n = p.reqs.length;
await p.locator('[placeholder^="Why is this the answer"]:visible').fill('B is measured in tesla (T) = N/(A·m).');
await chip(p, 'Published').click(); await p.waitForTimeout(300);
await p.getByRole('button', { name: 'Save', exact: true }).click(); await p.waitForTimeout(2500);
check('PATCH 200', since(n).some((r) => r.startsWith('PATCH /api/questions/') && r.endsWith('-> 200')), since(n).join(' | '));
check('DB: now published with edited_at + updated_by', (await dbq(`select status||'|'||(edited_at is not null)||'|'||(updated_by is not null) from questions where id='${draftId}'`)) === 'published|true|true');
check('DB: revision snapshot saved', (await dbq(`select count(*) from question_revisions where question_id='${draftId}'`)) === '1');
feed = await api(s2, 'GET', '/api/feed/today');
check('published question now reachable by students (eligible for feed)', feed.status === 200);
await p.getByText(/DRAFT-Q: What is the SI unit/).first().click(); await p.waitForTimeout(2000);
await p.getByRole('button', { name: 'More actions' }).first().click(); await p.waitForTimeout(500);
await p.getByRole('button', { name: /History/ }).first().click(); await p.waitForTimeout(1500);
check('History lists Version 1', await vis(p.getByText(/Version 1/)));
await chip(p, 'Restore this version').click(); await p.waitForTimeout(900);
await p.getByRole('button', { name: /^Restore/ }).last().click().catch(() => {}); await p.waitForTimeout(2500);
check('restore creates a new revision', Number(await dbq(`select count(*) from question_revisions where question_id='${draftId}'`)) >= 2);
check('restore reverted status to draft', (await dbq(`select status from questions where id='${draftId}'`)) === 'draft');
await p.keyboard.press('Escape').catch(() => {});
await p.getByRole('button', { name: 'More actions' }).first().click(); await p.waitForTimeout(500);
await p.getByRole('button', { name: /Archive/ }).first().click(); await p.waitForTimeout(1500);
const confirmArchive = p.getByRole('button', { name: /^Archive/ });
if ((await confirmArchive.count()) > 1) await confirmArchive.last().click();
await p.waitForTimeout(2200);
check('DB: archived (enabled=false)', (await dbq(`select enabled from questions where id='${draftId}'`)) === 'f');
check('archived question hidden from student eligibility', (await dbq(`select count(*) from questions where id='${draftId}' and enabled and status='published'`)) === '0');

step('Delete an unused question; lock a used one');
const tmp = await api(await tokenFor('teacher@stemri.local'), 'POST', '/api/questions', { section_id: await dbq("select id from sections where section_no='12.1'"), type: 'flashcard', text: 'TEMP-DELETE-ME one', answer: 'a', explanation: 'e' });
check('API created a throwaway question', tmp.status === 201);
const del = await api(await tokenFor('teacher@stemri.local'), 'DELETE', `/api/questions/${tmp.json.id}`);
check('unused question can be deleted', del.status === 200);
const used = await dbq("select id from questions where qtype='mcq' and enabled and status='published' limit 1");
await api(await tokenFor('s2@stemri.local'), 'POST', '/api/submissions', { question_id: used, daily_set_id: await dbq('select id from daily_sets limit 1'), selected_option: 0 });
const lock = await api(await tokenFor('teacher@stemri.local'), 'PATCH', `/api/questions/${used}`, { correct: 3 });
const inUse = Number(await dbq(`select count(*) from submissions where question_id='${used}'`)) > 0;
check('answered question: changing the correct option is refused (409)', !inUse || lock.status === 409, `${lock.status} ${JSON.stringify(lock.json)}`);
const delUsed = await api(await tokenFor('teacher@stemri.local'), 'DELETE', `/api/questions/${used}`);
check('answered question cannot be deleted (409)', !inUse || delUsed.status === 409, String(delUsed.status));

console.log('\nconsole/page errors:', p.logs.filter((l) => !/useNativeDriver|pointerEvents|status of 40[019]/.test(l)).slice(0, 6).join(' | ') || 'none');
const failed = summary(); await closeBrowser(); process.exit(failed ? 1 : 0);
